DELETE http://127.0.0.1:9000/pricelist/45
Accept: application/json

###
GET http://127.0.0.1:9000/pricelist/45
Accept: application/json

###
POST http://127.0.0.1:9000/pricelist
Content-Type: application/json

{
  "id": 45,
  "good": "MIG 35",
  "price": 100500
}

###
PUT http://127.0.0.1:9000/pricelist/46
Content-Type: application/json

{
  "id": 100,
  "good": "F-16",
  "price": 256
}


###
