DELETE http://127.0.0.1:9000/pricelist/5
Accept: application/json

###
GET http://127.0.0.1:9000/pricelist/13
Accept: application/json

###
POST http://127.0.0.1:9000/pricelist
Content-Type: application/json

{
  "id": 1,
  "good": "MIG 35",
  "price": 100500
}

###
PUT http://127.0.0.1:9000/pricelist/1
Content-Type: application/json

{
  "id": 1,
  "good": "F-16",
  "price": 256
}


###
