// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: oapi.proto

package pricelists

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PricelistId string `protobuf:"bytes,1,opt,name=pricelist_id,json=pricelistId,proto3" json:"pricelist_id,omitempty"`
	ItemId      string `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price       string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *PriceListItem) Reset() {
	*x = PriceListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceListItem) ProtoMessage() {}

func (x *PriceListItem) ProtoReflect() protoreflect.Message {
	mi := &file_oapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceListItem.ProtoReflect.Descriptor instead.
func (*PriceListItem) Descriptor() ([]byte, []int) {
	return file_oapi_proto_rawDescGZIP(), []int{0}
}

func (x *PriceListItem) GetPricelistId() string {
	if x != nil {
		return x.PricelistId
	}
	return ""
}

func (x *PriceListItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PriceListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PriceListItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_oapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_oapi_proto_rawDescGZIP(), []int{1}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PriceListRowsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListRows []*PriceListItem `protobuf:"bytes,1,rep,name=list_rows,json=listRows,proto3" json:"list_rows,omitempty"` // сообщения можно вкладывать друг в друга repeated - массив значений элемента
}

func (x *PriceListRowsResponse) Reset() {
	*x = PriceListRowsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceListRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceListRowsResponse) ProtoMessage() {}

func (x *PriceListRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceListRowsResponse.ProtoReflect.Descriptor instead.
func (*PriceListRowsResponse) Descriptor() ([]byte, []int) {
	return file_oapi_proto_rawDescGZIP(), []int{2}
}

func (x *PriceListRowsResponse) GetListRows() []*PriceListItem {
	if x != nil {
		return x.ListRows
	}
	return nil
}

var File_oapi_proto protoreflect.FileDescriptor

var file_oapi_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0d, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x14, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x15, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x32, 0xe7, 0x01, 0x0a,
	0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x1a, 0x0e, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x2e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oapi_proto_rawDescOnce sync.Once
	file_oapi_proto_rawDescData = file_oapi_proto_rawDesc
)

func file_oapi_proto_rawDescGZIP() []byte {
	file_oapi_proto_rawDescOnce.Do(func() {
		file_oapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_oapi_proto_rawDescData)
	})
	return file_oapi_proto_rawDescData
}

var file_oapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_oapi_proto_goTypes = []interface{}{
	(*PriceListItem)(nil),         // 0: PriceListItem
	(*ID)(nil),                    // 1: ID
	(*PriceListRowsResponse)(nil), // 2: PriceListRowsResponse
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_oapi_proto_depIdxs = []int32{
	0, // 0: PriceListRowsResponse.list_rows:type_name -> PriceListItem
	0, // 1: pricelists.CreatePriceListItem:input_type -> PriceListItem
	1, // 2: pricelists.DeletePriceList:input_type -> ID
	0, // 3: pricelists.UpdatePriceListItem:input_type -> PriceListItem
	1, // 4: pricelists.GetPriceList:input_type -> ID
	0, // 5: pricelists.CreatePriceListItem:output_type -> PriceListItem
	3, // 6: pricelists.DeletePriceList:output_type -> google.protobuf.Empty
	3, // 7: pricelists.UpdatePriceListItem:output_type -> google.protobuf.Empty
	2, // 8: pricelists.GetPriceList:output_type -> PriceListRowsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oapi_proto_init() }
func file_oapi_proto_init() {
	if File_oapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceListRowsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oapi_proto_goTypes,
		DependencyIndexes: file_oapi_proto_depIdxs,
		MessageInfos:      file_oapi_proto_msgTypes,
	}.Build()
	File_oapi_proto = out.File
	file_oapi_proto_rawDesc = nil
	file_oapi_proto_goTypes = nil
	file_oapi_proto_depIdxs = nil
}
