// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ID struct {
	PricelistID string `json:"pricelist_id"`
}

type NewPriceListItem struct {
	PricelistID string `json:"pricelist_id"`
	Name        string `json:"name"`
	Price       string `json:"price"`
}

type PriceListItem struct {
	PricelistID string `json:"pricelist_id"`
	ItemID      string `json:"item_id"`
	Name        string `json:"name"`
	Price       string `json:"price"`
}

type Result struct {
	Result *bool `json:"result"`
}

type UpdPriceListItem struct {
	PricelistID string `json:"pricelist_id"`
	ItemID      string `json:"item_id"`
	Name        string `json:"name"`
	Price       string `json:"price"`
}
