// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Pricelist defines model for Pricelist.
type Pricelist struct {
	Good  *string `json:"good,omitempty"`
	Id    *int    `json:"id,omitempty"`
	Price *int    `json:"price,omitempty"`
}

// PricelistEntityCreateViewJSONBody defines parameters for PricelistEntityCreateView.
type PricelistEntityCreateViewJSONBody Pricelist

// PricelistUpdateViewJSONBody defines parameters for PricelistUpdateView.
type PricelistUpdateViewJSONBody Pricelist

// PricelistEntityCreateViewJSONRequestBody defines body for PricelistEntityCreateView for application/json ContentType.
type PricelistEntityCreateViewJSONRequestBody PricelistEntityCreateViewJSONBody

// PricelistUpdateViewJSONRequestBody defines body for PricelistUpdateView for application/json ContentType.
type PricelistUpdateViewJSONRequestBody PricelistUpdateViewJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /pricelist)
	PricelistEntityCreateView(w http.ResponseWriter, r *http.Request)

	// (DELETE /pricelist/{id})
	PricelistDeleteView(w http.ResponseWriter, r *http.Request, id int)

	// (GET /pricelist/{id})
	PricelistListView(w http.ResponseWriter, r *http.Request, id int)

	// (PUT /pricelist/{id})
	PricelistUpdateView(w http.ResponseWriter, r *http.Request, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// PricelistEntityCreateView operation middleware
func (siw *ServerInterfaceWrapper) PricelistEntityCreateView(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PricelistEntityCreateView(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PricelistDeleteView operation middleware
func (siw *ServerInterfaceWrapper) PricelistDeleteView(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PricelistDeleteView(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PricelistListView operation middleware
func (siw *ServerInterfaceWrapper) PricelistListView(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PricelistListView(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PricelistUpdateView operation middleware
func (siw *ServerInterfaceWrapper) PricelistUpdateView(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PricelistUpdateView(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pricelist", wrapper.PricelistEntityCreateView)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/pricelist/{id}", wrapper.PricelistDeleteView)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pricelist/{id}", wrapper.PricelistListView)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/pricelist/{id}", wrapper.PricelistUpdateView)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVy27bMBD8FWLbo2I56aXRqa8cggRo0NelCAqGWsubSCRDrhIYhv69WEqO7NZx3UON",
	"niSvl8PZmSG1BOMa7yxajlAsIZo5Njq9XgUyWFNk+eGD8xiYMP1VOVfKkxceoYDIgWwFXQaUyjMXGs1Q",
	"AFmGDJi4ljbvIh8pv4JVVKpcVchHihgb1Vq6b1FRKUt6YLKMFQZBTsu2gf/S2T2V3M0tGoZOSmRnThYb",
	"Z1mbNBE2mmphhfO7eHz6evqmksrEuAYysLoRjAtn7QIyaIO0zpl9kefxUVcVhgk5IVZiNIE8k7NQwKez",
	"z1/U26vztbFv8OTH/PF0qD5giH3r8WQ6mQqC82i1JyjgVSpl4DXPk9C53zDB9U+xQsuG5yUUo09nlokX",
	"7wNqxm+Ej5BBwPsWI79z5WI1PtqEob2vySSU/DYKoZX58vYy4AwKeJGP6ciHaORjLpK0m/OP7mJio0yi",
	"M1ChgCUUHFrspBC9s7FP1Ml0emiCq/17E2e6rdO+m+1X2+dRZyG4IW26ilB8Xzsu11IencuXVHY9co2M",
	"Owz8kBoG67wOukHGIOhLoERe83wMZzopm7JmaxL9djKut2v+3MA9XRVbYzDGPVUaFqHIE5/VJ4MKdyX5",
	"kiIfWoa9oyeXVfyLDD5dSDoEvdiWyVE+GVx9vNhT7NS9O4kZ+HaX0l99qf915A58BV2SvVPslC5LeUR2",
	"QVf/0Q2U+LVJ970O13r/H86V1COGh5WD/Wcrl49Ld939DAAA//9h/RwB7AcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
